#include <cstdio>
#include <cstring>
#include <iostream>
#include <algorithm>
using namespace std;
const int INF=0x3f3f3f3f;
int n,m,q,p,sx,sy,sz,sd,ex,ey,ez,ed,ans;
bool vis[23][23][23];
inline void in(int &now)
{
    char Cget;now=0;while((Cget=getchar())>'9'||Cget<'0');
    while(Cget>='0'&&Cget<='9')now=now*10+Cget-'0',Cget=getchar();
}
void dfs(int x,int y,int z,int d,int step)
{
    if(step>=ans) return;
    if(x==ex&&ey==y&&ez==z&&d==ed)
    {
        ans=step;
        return;
    }
    if(step==12) return;
    if(x==ex&&y==ey&&z==ez) return;
    if(abs(ex-x)+abs(ey-y)+abs(ez-z)>(ans-step)*4) return;
    if(d==1)
    {
        if(z+2<=q)
            if(!vis[x][y][z+1]&&!vis[x][y][z+2])
            {
                vis[x][y][z+1]=vis[x][y][z+2]=true;
                if(y+2<=m)
                    if(!vis[x][y+1][z+2]&&!vis[x][y+2][z+2])
                    {
                        vis[x][y+1][z+2]=vis[x][y+2][z+2]=true;
                        dfs(x,y+2,z+2,5,step+1);
                        vis[x][y+1][z+2]=vis[x][y+2][z+2]=false;
                    }
                if(y-2>=1)
                    if(!vis[x][y-1][z+2]&&!vis[x][y-2][z+2])
                    {
                        vis[x][y-1][z+2]=vis[x][y-2][z+2]=true;
                        dfs(x,y-2,z+2,2,step+1);
                        vis[x][y-1][z+2]=vis[x][y-2][z+2]=false;
                    }
                if(x+2<=n)
                    if(!vis[x+1][y][z+2]&&!vis[x+2][y][z+2])
                    {
                        vis[x+1][y][z+2]=vis[x+2][y][z+2]=true;
                        dfs(x+2,y,z+2,3,step+1);
                        vis[x+1][y][z+2]=vis[x+2][y][z+2]=false;
                    }
                if(x-2>=1)
                    if(!vis[x-1][y][z+2]&&!vis[x-2][y][z+2])
                    {
                        vis[x-1][y][z+2]=vis[x-2][y][z+2]=true;
                        dfs(x-2,y,z+2,6,step+1);
                        vis[x-1][y][z+2]=vis[x-2][y][z+2]=false;
                    }
                vis[x][y][z+1]=vis[x][y][z+2]=false;
            }
        if(z-1>=1)
            if(!vis[x][y][z-1]&&!vis[x][y][z])
            {
                vis[x][y][z]=vis[x][y][z-1]=true;
                if(y+2<=m)
                    if(!vis[x][y+1][z-1]&&!vis[x][y+2][z-1])
                    {
                        vis[x][y+1][z-1]=vis[x][y+2][z-1]=true;
                        dfs(x,y+2,z-1,5,step+1);
                        vis[x][y+1][z-1]=vis[x][y+2][z-1]=false;
                    }
                if(y-2>=1)
                    if(!vis[x][y-1][z-1]&&!vis[x][y-2][z-1])
                    {
                        vis[x][y-1][z-1]=vis[x][y-2][z-1]=true;
                        dfs(x,y-2,z-1,2,step+1);
                        vis[x][y-1][z-1]=vis[x][y-2][z-1]=false;
                    }
                if(x+2<=n)
                    if(!vis[x+1][y][z-1]&&!vis[x+2][y][z-1])
                    {
                        vis[x+1][y][z-1]=vis[x+2][y][z-1]=true;
                        dfs(x+2,y,z-1,3,step+1);
                        vis[x+1][y][z-1]=vis[x+2][y][z-1]=false;
                    }
                if(x-2>=1)
                    if(!vis[x-1][y][z-1]&&!vis[x-2][y][z-1])
                    {
                        vis[x-1][y][z-1]=vis[x-2][y][z-1]=true;
                        dfs(x-2,y,z-1,6,step+1);
                        vis[x-1][y][z-1]=vis[x-2][y][z-1]=false;
                    }
                vis[x][y][z]=vis[x][y][z-1]=false;
            }
        if(z+3<=q)
            if(!vis[x][y][z+1]&&!vis[x][y][z+2]&&!vis[x][y][z+3])
            {
                vis[x][y][z+1]=vis[x][y][z+2]=vis[x][y][z+3]=true;
                if(y+1<=m)
                    if(!vis[x][y+1][z+3])
                    {
                        vis[x][y+1][z+3]=true;
                        dfs(x,y+1,z+3,5,step+1);
                        vis[x][y+1][z+3]=false;
                    }
                if(y-1<=m)
                    if(!vis[x][y-1][z+3])
                    {
                        vis[x][y-1][z+3]=true;
                        dfs(x,y-1,z+3,2,step+1);
                        vis[x][y-1][z+3]=false;
                    }
                if(x+1<=m)
                    if(!vis[x+1][y][z+3])
                    {
                        vis[x+1][y][z+3]=true;
                        dfs(x+1,y,z+3,3,step+1);
                        vis[x+1][y][z+3]=false;
                    }
                if(x-1<=m)
                    if(!vis[x-1][y][z+3])
                    {
                        vis[x-1][y][z+3]=true;
                        dfs(x-1,y,z+3,6,step+1);
                        vis[x-1][y][z+3]=false;
                    }
                vis[x][y][z+1]=vis[x][y][z+2]=vis[x][y][z+3]=false;
            }
        if(z-2>=1)
            if(!vis[x][y][z]&&!vis[x][y][z-1]&&!vis[x][y][z-2])
            {
                vis[x][y][z]=vis[x][y][z-1]=vis[x][y][z-2]=true;
                if(y+1<=m)
                    if(!vis[x][y+1][z-2])
                    {
                        vis[x][y+1][z-2]=true;
                        dfs(x,y+1,z-2,5,step+1);
                        vis[x][y+1][z-2]=false;
                    }
                if(y-1<=m)
                    if(!vis[x][y-1][z-2])
                    {
                        vis[x][y-1][z-2]=true;
                        dfs(x,y-1,z-2,2,step+1);
                        vis[x][y-1][z-2]=false;
                    }
                if(x+1<=m)
                    if(!vis[x+1][y][z-2])
                    {
                        vis[x+1][y][z-2]=true;
                        dfs(x+1,y,z-2,3,step+1);
                        vis[x+1][y][z-2]=false;
                    }
                if(x-1<=m)
                    if(!vis[x-1][y][z-2])
                    {
                        vis[x-1][y][z-2]=true;
                        dfs(x-1,y,z-2,6,step+1);
                        vis[x-1][y][z-2]=false;
                    }
                vis[x][y][z]=vis[x][y][z-2]=vis[x][y][z-1]=false;
            }
    }
    if(d==2)
    {
        if(y+1<=m)
            if(!vis[x][y][z]&&!vis[x][y+1][z])
            {
                vis[x][y][z]=vis[x][y+1][z]=true;
                if(z+2<=q)
                    if(!vis[x][y+1][z+2]&&!vis[x][y+1][z+1])
                    {
                        vis[x][y+1][z+2]=vis[x][y+1][z+1]=true;
                        dfs(x,y+1,z+2,1,step+1);
                        vis[x][y+1][z+2]=vis[x][y+1][z+1]=false;
                    }
                if(z-2>=1)
                    if(!vis[x][y+1][z-1]&&!vis[x][y+1][z-2])
                    {
                        vis[x][y+1][z-1]=vis[x][y+1][z-2]=true;
                        dfs(x,y+1,z-2,4,step+1);
                        vis[x][y+1][z-1]=vis[x][y+1][z-2]=false;
                    }
                if(x+2<=n)
                    if(!vis[x+1][y+1][z]&&!vis[x+2][y+1][z])
                    {
                        vis[x+1][y+1][z]=vis[x+2][y+1][z]=true;
                        dfs(x+2,y+1,z,3,step+1);
                        vis[x+1][y+1][z]=vis[x+2][y+1][z]=false;
                    }
                if(x-2>=1)
                    if(!vis[x-1][y+1][z]&&!vis[x-2][y+1][z])
                    {
                        vis[x-1][y+1][z]=vis[x-2][y+1][z]=true;
                        dfs(x-2,y+1,z,6,step+1);
                        vis[x-1][y+1][z]=vis[x-2][y+1][z]=false;
                    }
                vis[x][y][z]=vis[x][y+1][z]=false;
            }
        if(y-2>=1)
            if(!vis[x][y-1][z]&&!vis[x][y-2][z])
            {
                vis[x][y-1][z]=vis[x][y-2][z]=true;
                if(z+2<=q)
                    if(!vis[x][y-2][z+1]&&!vis[x][y-2][z+2])
                    {
                        vis[x][y-2][z+1]=vis[x][y-2][z+2]=true;
                        dfs(x,y-2,z+2,1,step+1);
                        vis[x][y-2][z+1]=vis[x][y-2][z+2]=false;
                    }
                if(z-2>=1)
                    if(!vis[x][y-2][z-1]&&!vis[x][y-2][z-2])
                    {
                        vis[x][y-2][z-1]=vis[x][y-2][z-2]=true;
                        dfs(x,y-2,z-2,4,step+1);
                        vis[x][y-2][z-1]=vis[x][y-2][z-2]=false;
                    }
                if(x+2<=n)
                    if(!vis[x+1][y-2][z]&&!vis[x+2][y-2][z])
                    {
                        vis[x+1][y-2][z]=vis[x+2][y-2][z]=true;
                        dfs(x+2,y-2,z,3,step+1);
                        vis[x+1][y-2][z]=vis[x+2][y-2][z]=false;
                    }
                if(x-2>=1)
                    if(!vis[x-1][y-2][z]&&!vis[x-2][y-2][z])
                    {
                        vis[x-1][y-2][z]=vis[x-2][y-2][z]=true;
                        dfs(x-2,y-2,z,6,step+1);
                        vis[x-1][y-2][z]=vis[x-2][y-2][z]=false;
                    }
                vis[x][y-1][z]=vis[x][y-2][z]=false;
            }
        if(y+2<=m)
            if(!vis[x][y][z]&&!vis[x][y+1][z]&&!vis[x][y+2][z])
            {
                vis[x][y][z]=vis[x][y+1][z]=vis[x][y+2][z]=true;
                if(z+1<=q)
                    if(!vis[x][y+2][z+1])
                    {
                        vis[x][y+2][z+1]=true;
                        dfs(x,y+2,z+1,1,step+1);
                        vis[x][y+2][z+1]=false;
                    }
                if(z-1>=1)
                    if(!vis[x][y+2][z-1])
                    {
                        vis[x][y+2][z-1]=true;
                        dfs(x,y+2,z-1,4,step+1);
                        vis[x][y+2][z-1]=false;
                    }
                if(x+1<=n)
                    if(!vis[x+1][y+2][z])
                    {
                        vis[x+1][y+2][z]=true;
                        dfs(x+1,y+2,z,3,step+1);
                        vis[x+1][y+2][z]=false;
                    }
                if(x-1>=1)
                    if(!vis[x-1][y+2][z])
                    {
                        vis[x-1][y+2][z]=true;
                        dfs(x-1,y+2,z,6,step+1);
                        vis[x-1][y+2][z]=false;
                    }
                vis[x][y][z]=vis[x][y+1][z]=vis[x][y+2][z]=false;
            }
        if(y-3>=1)
            if(!vis[x][y-1][z]&&!vis[x][y-2][z]&&!vis[x][y-3][z])
            {
                vis[x][y-1][z]=vis[x][y-2][z]=vis[x][y-3][z]=true;
                if(z+1<=q)
                    if(!vis[x][y-3][z+1])
                    {
                        vis[x][y-3][z+1]=true;
                        dfs(x,y-3,z+1,1,step+1);
                        vis[x][y-3][z+1]=false;
                    }
                if(z-1>=1)
                    if(!vis[x][y-3][z-1])
                    {
                        vis[x][y-3][z-1]=true;
                        dfs(x,y-3,z-1,4,step+1);
                        vis[x][y-3][z-1]=false;
                    }
                if(x+1<=n)
                    if(!vis[x+1][y-3][z])
                    {
                        vis[x+1][y-3][z]=true;
                        dfs(x+1,y-3,z,3,step+1);
                        vis[x+1][y-3][z]=false;
                    }
                if(x-1>=1)
                    if(!vis[x-1][y-3][z])
                    {
                        vis[x-1][y-3][z]=true;
                        dfs(x-1,y-3,z,6,step+1);
                        vis[x-1][y-3][z]=false;
                    }
                vis[x][y-1][z]=vis[x][y-2][z]=vis[x][y-3][z]=false;
            }
    }
    if(d==3)
    {
        if(x+2<=n)
            if(!vis[x+1][y][z]&&!vis[x+2][y][z])
            {
                vis[x+1][y][z]=vis[x+2][y][z]=true;
                if(z+2<=q)
                    if(!vis[x+2][y][z+1]&&!vis[x+2][y][z+2])
                    {
                        vis[x+2][y][z+1]=vis[x+2][y][z+2]=true;
                        dfs(x+2,y,z+2,1,step+1);
                        vis[x+2][y][z+1]=vis[x+2][y][z+2]=false;
                    }
                if(z-2>=1)
                    if(!vis[x+2][y][z-1]&&!vis[x+2][y][z-2])
                    {
                        vis[x+2][y][z-1]=vis[x+2][y][z-2]=true;
                        dfs(x+2,y,z-2,4,step+1);
                        vis[x+2][y][z-1]=vis[x+2][y][z-2]=false;
                    }
                if(y+2<=m)
                    if(!vis[x+2][y+1][z]&&!vis[x+2][y+2][z])
                    {
                        vis[x+2][y+1][z]=vis[x+2][y+2][z]=true;
                        dfs(x+2,y+2,z,5,step+1);
                        vis[x+2][y+1][z]=vis[x+2][y+2][z]=false;
                    }
                if(y-2>=1)
                    if(!vis[x+2][y-1][z]&&!vis[x+2][y-2][z])
                    {
                        vis[x+2][y-1][z]=vis[x+2][y-2][z]=true;
                        dfs(x+2,y-2,z,2,step+1);
                        vis[x+2][y-1][z]=vis[x+2][y-2][z]=false;
                    }
                vis[x+1][y][z]=vis[x+2][y][z]=false;
            }
        if(x-1>=1)
            if(!vis[x][y][z]&&!vis[x-1][y][z])
            {
                vis[x][y][z]=vis[x-1][y][z]=true;
                if(z+2<=q)
                    if(!vis[x-1][y][z+1]&&!vis[x-1][y][z+2])
                    {
                        vis[x-1][y][z+1]=vis[x-1][y][z+2]=true;
                        dfs(x-1,y,z+2,1,step+1);
                        vis[x-1][y][z+1]=vis[x-1][y][z+2]=false;
                    }
                if(z-2>=1)
                    if(!vis[x-1][y][z-1]&&!vis[x-1][y][z-2])
                    {
                        vis[x-1][y][z-1]=vis[x-1][y][z-2]=true;
                        dfs(x-1,y,z-2,4,step+1);
                        vis[x-1][y][z-1]=vis[x-1][y][z-2]=false;
                    }
                if(y+2<=m)
                    if(!vis[x-1][y+1][z]&&!vis[x-1][y+2][z])
                    {
                        vis[x-1][y+1][z]=vis[x-1][y+2][z]=true;
                        dfs(x-1,y+2,z,5,step+1);
                        vis[x-1][y+1][z]=vis[x-1][y+2][z]=false;
                    }
                if(y-2>=1)
                    if(!vis[x-1][y-1][z]&&!vis[x-1][y-2][z])
                    {
                        vis[x-1][y-1][z]=vis[x-1][y-2][z]=true;
                        dfs(x-1,y-2,z,2,step+1);
                        vis[x-1][y-1][z]=vis[x-1][y-2][z]=false;
                    }
                vis[x][y][z]=vis[x-1][y][z]=false;
            }
        if(x+3<=n)
            if(!vis[x+1][y][z]&&!vis[x+2][y][z]&&!vis[x+3][y][z])
            {
                vis[x+1][y][z]=vis[x+2][y][z]=vis[x+3][y][z]=true;
                if(y+1<=m)
                    if(!vis[x+3][y+1][z])
                    {
                        vis[x+3][y+1][z]=true;
                        dfs(x+3,y+1,z,5,step+1);
                        vis[x+3][y+1][z]=false;
                    }
                if(y-1>=1)
                    if(!vis[x+3][y-1][z])
                    {
                        vis[x+3][y-1][z]=true;
                        dfs(x+3,y-1,z,2,step+1);
                        vis[x+3][y-1][z]=false;
                    }
                if(z+1<=q)
                    if(!vis[x+3][y][z+1])
                    {
                        vis[x+3][y][z+1]=true;
                        dfs(x+3,y,z+1,1,step+1);
                        vis[x+3][y][z+1]=false;
                    }
                if(z-1>=1)
                    if(!vis[x+3][y][z-1])
                    {
                        vis[x+3][y][z-1]=true;
                        dfs(x+3,y,z-1,4,step+1);
                        vis[x+3][y][z-1]=false;
                    }
                vis[x+1][y][z]=vis[x+2][y][z]=vis[x+3][y][z]=false;
            }
        if(x-2>=1)
            if(!vis[x][y][z]&&!vis[x-1][y][z]&&!vis[x-2][y][z])
            {
                vis[x][y][z]=vis[x-1][y][z]=vis[x-2][y][z]=true;
                if(y+1<=m)
                    if(!vis[x-2][y+1][z])
                    {
                        vis[x-2][y+1][z]=true;
                        dfs(x-2,y+1,z,5,step+1);
                        vis[x-2][y+1][z]=false;
                    }
                if(y-1>=1)
                    if(!vis[x-2][y-1][z])
                    {
                        vis[x-2][y-1][z]=true;
                        dfs(x-2,y-1,z,2,step+1);
                        vis[x-2][y-1][z]=false;
                    }
                if(z+1<=q)
                    if(!vis[x-2][y][z+1])
                    {
                        vis[x-2][y][z+1]=true;
                        dfs(x-2,y,z+1,1,step+1);
                        vis[x-2][y][z+1]=false;
                    }
                if(z-1>=1)
                    if(!vis[x-2][y][z-1])
                    {
                        vis[x-2][y][z-1]=true;
                        dfs(x-2,y,z-1,4,step+1);
                        vis[x-2][y][z-1]=false;
                    }
                vis[x][y][z]=vis[x-1][y][z]=vis[x-2][y][z]=false;
            }
    }
    if(d==4)
    {
        if(z+1<=q)
            if(!vis[x][y][z]&&!vis[x][y][z+1])
            {
                vis[x][y][z]=vis[x][y][z+1]=true;
                if(y+2<=m)
                    if(!vis[x][y+1][z+1]&&!vis[x][y+2][z+1])
                    {
                        vis[x][y+1][z+1]=vis[x][y+2][z+1]=true;
                        dfs(x,y+2,z+1,5,step+1);
                        vis[x][y+1][z+1]=vis[x][y+2][z+1]=false;
                    }
                if(y-2>=1)
                    if(!vis[x][y-1][z+1]&&!vis[x][y-2][z+1])
                    {
                        vis[x][y-1][z+1]=vis[x][y-2][z+1]=true;
                        dfs(x,y-2,z+1,2,step+1);
                        vis[x][y-1][z+1]=vis[x][y-2][z+1]=false;
                    }
                if(x+2<=n)
                    if(!vis[x+1][y][z+1]&&!vis[x+2][y][z+1])
                    {
                        vis[x+1][y][z+1]=vis[x+2][y][z+1]=true;
                        dfs(x+2,y,z+1,3,step+1);
                        vis[x+1][y][z+1]=vis[x+2][y][z+1]=false;
                    }
                if(x-2>=1)
                    if(!vis[x-1][y][z+1]&&!vis[x-2][y][z+1])
                    {
                        vis[x-1][y][z+1]=vis[x-2][y][z+1]=true;
                        dfs(x-2,y,z+1,6,step+1);
                        vis[x-1][y][z+1]=vis[x-2][y][z+1]=false;
                    }
                vis[x][y][z]=vis[x][y][z+1]=false;
            }
        if(z-2>=1)
            if(!vis[x][y][z-2]&&!vis[x][y][z-1])
            {
                vis[x][y][z-1]=vis[x][y][z-2]=true;
                if(y+2<=m)
                    if(!vis[x][y+1][z-2]&&!vis[x][y+2][z-2])
                    {
                        vis[x][y+1][z-2]=vis[x][y+2][z-2]=true;
                        dfs(x,y+2,z-2,5,step+1);
                        vis[x][y+1][z-2]=vis[x][y+2][z-2]=false;
                    }
                if(y-2>=1)
                    if(!vis[x][y-1][z-2]&&!vis[x][y-2][z-2])
                    {
                        vis[x][y-1][z-2]=vis[x][y-2][z-2]=true;
                        dfs(x,y-2,z-2,2,step+1);
                        vis[x][y-1][z-2]=vis[x][y-2][z-2]=false;
                    }
                if(x+2<=n)
                    if(!vis[x+1][y][z-2]&&!vis[x+2][y][z-2])
                    {
                        vis[x+1][y][z-2]=vis[x+2][y][z-2]=true;
                        dfs(x+2,y,z-2,3,step+1);
                        vis[x+1][y][z-2]=vis[x+2][y][z-2]=false;
                    }
                if(x-2>=1)
                    if(!vis[x-1][y][z-2]&&!vis[x-2][y][z-2])
                    {
                        vis[x-1][y][z-2]=vis[x-2][y][z-2]=true;
                        dfs(x-2,y,z-2,6,step+1);
                        vis[x-1][y][z-2]=vis[x-2][y][z-2]=false;
                    }
                vis[x][y][z-1]=vis[x][y][z-2]=false;
            }
        if(z+2<=q)
            if(!vis[x][y][z]&&!vis[x][y][z+1]&&!vis[x][y][z+2])
            {
                vis[x][y][z+1]=vis[x][y][z]=vis[x][y][z+2]=true;
                if(y+1<=m)
                    if(!vis[x][y+1][z+2])
                    {
                        vis[x][y+1][z+2]=true;
                        dfs(x,y+1,z+2,5,step+1);
                        vis[x][y+1][z+2]=false;
                    }
                if(y-1<=m)
                    if(!vis[x][y-1][z+2])
                    {
                        vis[x][y-1][z+2]=true;
                        dfs(x,y-1,z+2,2,step+1);
                        vis[x][y-1][z+2]=false;
                    }
                if(x+1<=m)
                    if(!vis[x+1][y][z+2])
                    {
                        vis[x+1][y][z+2]=true;
                        dfs(x+1,y,z+2,3,step+1);
                        vis[x+1][y][z+2]=false;
                    }
                if(x-1<=m)
                    if(!vis[x-1][y][z+2])
                    {
                        vis[x-1][y][z+2]=true;
                        dfs(x-1,y,z+2,6,step+1);
                        vis[x-1][y][z+2]=false;
                    }
                vis[x][y][z+1]=vis[x][y][z+2]=vis[x][y][z]=false;
            }
        if(z-3>=1)
            if(!vis[x][y][z-1]&&!vis[x][y][z-2]&&!vis[x][y][z-3])
            {
                vis[x][y][z-1]=vis[x][y][z-2]=vis[x][y][z-3]=true;
                if(y+1<=m)
                    if(!vis[x][y+1][z-3])
                    {
                        vis[x][y+1][z-3]=true;
                        dfs(x,y+1,z-3,5,step+1);
                        vis[x][y+1][z-3]=false;
                    }
                if(y-1<=m)
                    if(!vis[x][y-1][z-3])
                    {
                        vis[x][y-1][z-3]=true;
                        dfs(x,y-1,z-3,2,step+1);
                        vis[x][y-1][z-3]=false;
                    }
                if(x+1<=m)
                    if(!vis[x+1][y][z-3])
                    {
                        vis[x+1][y][z-3]=true;
                        dfs(x+1,y,z-2,3,step+1);
                        vis[x+1][y][z-3]=false;
                    }
                if(x-1<=m)
                    if(!vis[x-1][y][z-3])
                    {
                        vis[x-1][y][z-3]=true;
                        dfs(x-1,y,z-3,6,step+1);
                        vis[x-1][y][z-3]=false;
                    }
                vis[x][y][z-3]=vis[x][y][z-2]=vis[x][y][z-1]=false;
            }
    }
    if(d==5)
    {
        if(y+2<=m)
            if(!vis[x][y+1][z]&&!vis[x][y+2][z])
            {
                vis[x][y+1][z]=vis[x][y+2][z]=true;
                if(z+2<=q)
                    if(!vis[x][y+2][z+2]&&!vis[x][y+2][z+1])
                    {
                        vis[x][y+2][z+2]=vis[x][y+2][z+1]=true;
                        dfs(x,y+2,z+2,1,step+1);
                        vis[x][y+2][z+2]=vis[x][y+2][z+1]=false;
                    }
                if(z-2>=1)
                    if(!vis[x][y+2][z-1]&&!vis[x][y+2][z-2])
                    {
                        vis[x][y+2][z-1]=vis[x][y+2][z-2]=true;
                        dfs(x,y+2,z-2,4,step+1);
                        vis[x][y+2][z-1]=vis[x][y+2][z-2]=false;
                    }
                if(x+2<=n)
                    if(!vis[x+1][y+2][z]&&!vis[x+2][y+2][z])
                    {
                        vis[x+1][y+2][z]=vis[x+2][y+2][z]=true;
                        dfs(x+2,y+2,z,3,step+1);
                        vis[x+1][y+2][z]=vis[x+2][y+2][z]=false;
                    }
                if(x-2>=1)
                    if(!vis[x-1][y+2][z]&&!vis[x-2][y+2][z])
                    {
                        vis[x-1][y+2][z]=vis[x-2][y+2][z]=true;
                        dfs(x-2,y+2,z,6,step+1);
                        vis[x-1][y+2][z]=vis[x-2][y+2][z]=false;
                    }
                vis[x][y+1][z]=vis[x][y+2][z]=false;
            }
        if(y-1>=1)
            if(!vis[x][y][z]&&!vis[x][y-1][z])
            {
                vis[x][y-1][z]=vis[x][y][z]=true;
                if(z+2<=q)
                    if(!vis[x][y-1][z+1]&&!vis[x][y-1][z+2])
                    {
                        vis[x][y-1][z+1]=vis[x][y-1][z+2]=true;
                        dfs(x,y-1,z+2,1,step+1);
                        vis[x][y-1][z+1]=vis[x][y-1][z+2]=false;
                    }
                if(z-2>=1)
                    if(!vis[x][y-1][z-1]&&!vis[x][y-1][z-2])
                    {
                        vis[x][y-1][z-1]=vis[x][y-1][z-2]=true;
                        dfs(x,y-1,z-2,4,step+1);
                        vis[x][y-1][z-1]=vis[x][y-1][z-2]=false;
                    }
                if(x+2<=n)
                    if(!vis[x+1][y-1][z]&&!vis[x+2][y-1][z])
                    {
                        vis[x+1][y-1][z]=vis[x+2][y-1][z]=true;
                        dfs(x+2,y-1,z,3,step+1);
                        vis[x+1][y-1][z]=vis[x+2][y-1][z]=false;
                    }
                if(x-2>=1)
                    if(!vis[x-1][y-1][z]&&!vis[x-2][y-1][z])
                    {
                        vis[x-1][y-1][z]=vis[x-2][y-1][z]=true;
                        dfs(x-2,y-1,z,6,step+1);
                        vis[x-1][y-1][z]=vis[x-2][y-1][z]=false;
                    }
                vis[x][y][z]=vis[x][y-1][z]=false;
            }
        if(y+3<=m)
            if(!vis[x][y+1][z]&&!vis[x][y+2][z]&&!vis[x][y+3][z])
            {
                vis[x][y+1][z]=vis[x][y+2][z]=vis[x][y+3][z]=true;
                if(z+1<=q)
                    if(!vis[x][y+3][z+1])
                    {
                        vis[x][y+3][z+1]=true;
                        dfs(x,y+3,z+1,1,step+1);
                        vis[x][y+3][z+1]=false;
                    }
                if(z-1>=1)
                    if(!vis[x][y+3][z-1])
                    {
                        vis[x][y+3][z-1]=true;
                        dfs(x,y+3,z-1,4,step+1);
                        vis[x][y+3][z-1]=false;
                    }
                if(x+1<=n)
                    if(!vis[x+1][y+3][z])
                    {
                        vis[x+1][y+3][z]=true;
                        dfs(x+1,y+3,z,3,step+1);
                        vis[x+1][y+3][z]=false;
                    }
                if(x-1>=1)
                    if(!vis[x-1][y+3][z])
                    {
                        vis[x-1][y+3][z]=true;
                        dfs(x-1,y+3,z,6,step+1);
                        vis[x-1][y+3][z]=false;
                    }
                vis[x][y+3][z]=vis[x][y+1][z]=vis[x][y+2][z]=false;
            }
        if(y-2>=1)
            if(!vis[x][y-1][z]&&!vis[x][y-2][z]&&!vis[x][y][z])
            {
                vis[x][y-1][z]=vis[x][y-2][z]=vis[x][y][z]=true;
                if(z+1<=q)
                    if(!vis[x][y-2][z+1])
                    {
                        vis[x][y-2][z+1]=true;
                        dfs(x,y-2,z+1,1,step+1);
                        vis[x][y-2][z+1]=false;
                    }
                if(z-1>=1)
                    if(!vis[x][y-2][z-1])
                    {
                        vis[x][y-2][z-1]=true;
                        dfs(x,y-2,z-1,4,step+1);
                        vis[x][y-2][z-1]=false;
                    }
                if(x+1<=n)
                    if(!vis[x+1][y-2][z])
                    {
                        vis[x+1][y-2][z]=true;
                        dfs(x+1,y-2,z,3,step+1);
                        vis[x+1][y-2][z]=false;
                    }
                if(x-1>=1)
                    if(!vis[x-1][y-2][z])
                    {
                        vis[x-1][y-2][z]=true;
                        dfs(x-1,y-2,z,6,step+1);
                        vis[x-1][y-2][z]=false;
                    }
                vis[x][y-1][z]=vis[x][y-2][z]=vis[x][y][z]=false;
            }
    }
    if(d==6)
    {
        if(x+1<=n)
            if(!vis[x][y][z]&&!vis[x+1][y][z])
            {
                vis[x][y][z]=vis[x+1][y][z]=true;
                if(z+2<=q)
                    if(!vis[x+1][y][z+1]&&!vis[x+1][y][z+2])
                    {
                        vis[x+1][y][z+1]=vis[x+1][y][z+2]=true;
                        dfs(x+1,y,z+2,1,step+1);
                        vis[x+1][y][z+1]=vis[x+1][y][z+2]=false;
                    }
                if(z-2>=1)
                    if(!vis[x+1][y][z-1]&&!vis[x+1][y][z-2])
                    {
                        vis[x+1][y][z-1]=vis[x+1][y][z-2]=true;
                        dfs(x+1,y,z-2,4,step+1);
                        vis[x+1][y][z-1]=vis[x+1][y][z-2]=false;
                    }
                if(y+2<=m)
                    if(!vis[x+1][y+1][z]&&!vis[x+1][y+2][z])
                    {
                        vis[x+1][y+1][z]=vis[x+1][y+2][z]=true;
                        dfs(x+1,y+2,z,5,step+1);
                        vis[x+1][y+1][z]=vis[x+1][y+2][z]=false;
                    }
                if(y-2>=1)
                    if(!vis[x+1][y-1][z]&&!vis[x+1][y-2][z])
                    {
                        vis[x+1][y-1][z]=vis[x+1][y-2][z]=true;
                        dfs(x+1,y-2,z,2,step+1);
                        vis[x+1][y-1][z]=vis[x+1][y-2][z]=false;
                    }
                vis[x+1][y][z]=vis[x][y][z]=false;
            }
        if(x-2>=1)
            if(!vis[x-1][y][z]&&!vis[x-2][y][z])
            {
                vis[x-1][y][z]=vis[x-2][y][z]=true;
                if(z+2<=q)
                    if(!vis[x-2][y][z+1]&&!vis[x-2][y][z+2])
                    {
                        vis[x-2][y][z+1]=vis[x-2][y][z+2]=true;
                        dfs(x-2,y,z+2,1,step+1);
                        vis[x-2][y][z+1]=vis[x-2][y][z+2]=false;
                    }
                if(z-2>=1)
                    if(!vis[x-2][y][z-1]&&!vis[x-2][y][z-2])
                    {
                        vis[x-2][y][z-1]=vis[x-2][y][z-2]=true;
                        dfs(x-2,y,z-2,4,step+1);
                        vis[x-2][y][z-1]=vis[x-2][y][z-2]=false;
                    }
                if(y+2<=m)
                    if(!vis[x-2][y+1][z]&&!vis[x-2][y+2][z])
                    {
                        vis[x-2][y+1][z]=vis[x-2][y+2][z]=true;
                        dfs(x-2,y+2,z,5,step+1);
                        vis[x-2][y+1][z]=vis[x-2][y+2][z]=false;
                    }
                if(y-2>=1)
                    if(!vis[x-2][y-1][z]&&!vis[x-2][y-2][z])
                    {
                        vis[x-2][y-1][z]=vis[x-2][y-2][z]=true;
                        dfs(x-2,y-2,z,2,step+1);
                        vis[x-2][y-1][z]=vis[x-2][y-2][z]=false;
                    }
                vis[x-2][y][z]=vis[x-1][y][z]=false;
            }
        if(x+2<=n)
            if(!vis[x+1][y][z]&&!vis[x+2][y][z]&&!vis[x][y][z])
            {
                vis[x+1][y][z]=vis[x+2][y][z]=vis[x][y][z]=true;
                if(y+1<=m)
                    if(!vis[x+2][y+1][z])
                    {
                        vis[x+2][y+1][z]=true;
                        dfs(x+2,y+1,z,5,step+1);
                        vis[x+2][y+1][z]=false;
                    }
                if(y-1>=1)
                    if(!vis[x+2][y-1][z])
                    {
                        vis[x+2][y-1][z]=true;
                        dfs(x+2,y-1,z,2,step+1);
                        vis[x+2][y-1][z]=false;
                    }
                if(z+1<=q)
                    if(!vis[x+2][y][z+1])
                    {
                        vis[x+2][y][z+1]=true;
                        dfs(x+2,y,z+1,1,step+1);
                        vis[x+2][y][z+1]=false;
                    }
                if(z-1>=1)
                    if(!vis[x+2][y][z-1])
                    {
                        vis[x+2][y][z-1]=true;
                        dfs(x+2,y,z-1,4,step+1);
                        vis[x+2][y][z-1]=false;
                    }
                vis[x+1][y][z]=vis[x+2][y][z]=vis[x][y][z]=false;
            }
        if(x-3>=1)
            if(!vis[x-3][y][z]&&!vis[x-1][y][z]&&!vis[x-2][y][z])
            {
                vis[x-3][y][z]=vis[x-1][y][z]=vis[x-2][y][z]=true;
                if(y+1<=m)
                    if(!vis[x-3][y+1][z])
                    {
                        vis[x-3][y+1][z]=true;
                        dfs(x-3,y+1,z,5,step+1);
                        vis[x-3][y+1][z]=false;
                    }
                if(y-1>=1)
                    if(!vis[x-3][y-1][z])
                    {
                        vis[x-3][y-1][z]=true;
                        dfs(x-3,y-1,z,2,step+1);
                        vis[x-3][y-1][z]=false;
                    }
                if(z+1<=q)
                    if(!vis[x-3][y][z+1])
                    {
                        vis[x-3][y][z+1]=true;
                        dfs(x-3,y,z+1,1,step+1);
                        vis[x-3][y][z+1]=false;
                    }
                if(z-1>=1)
                    if(!vis[x-3][y][z-1])
                    {
                        vis[x-3][y][z-1]=true;
                        dfs(x-3,y,z-1,4,step+1);
                        vis[x-3][y][z-1]=false;
                    }
                vis[x-3][y][z]=vis[x-1][y][z]=vis[x-2][y][z]=false;
            }
    }
}
int main()
{
    freopen("blessyou.in","r",stdin);
    freopen("blessyou.out","w",stdout);
    in(n),in(m),in(q),in(p);
    char op[4];
    in(sx),in(sy),in(sz),scanf("%s",op);
    if(op[0]=='x')
        if(sx==1) sd=6;
        else sd=3;
    else
        if(op[0]=='y')
            if(sy==1) sd=2;
            else sd=5;
    else
        if(sz==1) sd=4;
        else sd=1;
    in(ex),in(ey),in(ez),scanf("%s",op);
    if(op[0]=='x')
        if(ex==1) ed=6;
        else ed=3;
    else
        if(op[0]=='y')
            if(ey==1) ed=2;
            else ed=5;
    else
        if(ez==1) ed=4;
        else ed=1;
    int tmpx,tmpy,tmpz;
    for(int i=1;i<=p;i++)
    {
        in(tmpx),in(tmpy),in(tmpz);
        vis[tmpx][tmpy][tmpz]=true;
    }
    ans=13;
    dfs(sx,sy,sz,sd,0);
    if(ans==13) cout<<"Dream Battle";
    else cout<<ans;
    return 0;
}
